### ISSUE TITLE
As a <developer>, I want <to setup an electron app>, so that <I can use it to deploy the project on a kiosk environment>.

### ISSUE THREAD

**Issue by GagsdName** [cns-iu/macroscope-kiosk#14]

**Comment by bherr2** [comment]
I have a script that I use with `npm install nativefier` written with bash (below), but you should convert it to use their javascript api and create a script with that which can be triggered by an npm command. `npm run build:kiosk`.

Note: The exact URL is likely to change.

Nativefier API: https://github.com/jiahaog/nativefier/blob/master/docs/api.md#programmatic-api

build-macroscope-kiosk.sh
```bash
#!/bin/bash

URL="http://idemo.cns.iu.edu/#!/"
#URL="https://demo.cns.iu.edu/macroscope-kiosk-13/#!/"
nativefier -p windows -a x64 --inject ~/bin/macroscope-zoom-fix.js --insecure --full-screen --hide-window-frame --disable-context-menu --disable-dev-tools --always-on-top --ignore-gpu-blacklist $URL macroscope-kiosk
```

macroscope-zoom-fix.js
```javascript
var webFrame = require('electron').webFrame
webFrame.setVisualZoomLevelLimits(1, 1);
webFrame.setLayoutZoomLevelLimits(0, 0);
```
