### ISSUE TITLE
As a <museum-visitor>, I want <to be attracted to the exhibit>, so that <I can better enjoy my experience and to learn something about this particular topic>.

### ISSUE THREAD

**Issue by GagsdName** [cns-iu/macroscope-kiosk#15]
##### Acceptance Criteria - 

Ensure the museum visitor is attracted to the exhibit by presenting the animated screensaver which should play in a loop.

Specifically ensure the following - 

- [x] When no interaction has occurred with the kiosk for seven minutes the screensaver will activate.
- [x] The screensaver has text and a video that loops in the background. The video has short segments of select macroscopes, chosen because of their vibrancy and animation. 
- [x] Video will loop.
- [x] Behind the text is a black to transparent gradient, going from top to bottom, respectively.
- [x] The page should fade away when a user touches it. After seven minutes of idle time it should fade in. Fade time will be between 600 and 1500. Because of size, this will require tweaking. 
- [x] The screensaver should ALWAYS return to home page during fade out.

**Comment by GagsdName** [comment]
Clarify - " Because of size, this will require tweaking." from Leonard.
what does size have to do with the timing? 
why is it needed ?

**Comment by KalaRaja** [comment]
added another acceptance critera.
