### ISSUE TITLE
Update 14th Iteration iframe URLs

### ISSUE THREAD

**Issue by bherr2** [cns-iu/macroscope-kiosk#46]
In no particular order, here are the links to the kiosk versions of each of the 14th iteration macroscopes:

* Tweetoscope: http://tweetoscope.iscpif.fr/COP21/kiosk.html?lang=EN
* Rhythm of Food: http://clients.stefaner.eu/google/food/ps/
* Violence Info: http://apps.who.int/violence-info/
* The Appalachian Overdose Mapping Tool: http://overdosemappingtool.norc.org/nolinks.html

**Comment by gurjaspalbedi** [comment]
Hi @bherr2 , We need clarity on the following iterations and their specific macroscopes.

1. Iteration - 11, Macroscope -4: The URL we have is not a website URL. The URL is: ![image.png](https://images.zenhubusercontent.com/5b9290b9fb5dec0b0d9cb85b/a39b6302-494a-4d75-955b-d35e820c66a2)

2. Iteration - 12, Macrscopes-2,4,5 - We do not have any information about these.

3. Iteration - 12, Macrscope - 6 - Getting CORS error while loading in the iframe. URL: ![image.png](https://images.zenhubusercontent.com/5b9290b9fb5dec0b0d9cb85b/e1ddfb65-e757-49bf-b463-7bbfc203951f)

4. Iteration - 13, Macroscope - 1 - Displays not found, URL:  ![image.png](https://images.zenhubusercontent.com/5b9290b9fb5dec0b0d9cb85b/2f14766e-5727-426d-a5fc-33886a0f3669)

**Comment by bherr2** [comment]
For (1) - http://idemo.cns.iu.edu/macroscopes/ChartingCulture.webm
For (2) -- I'm looking into this now.
For (3) - http://idemo.cns.iu.edu/macroscopes/hathi/
For (4) - http://cosmicweb.kimalbrecht.com/viz/#2

I saw this one too, but not sure if its used?
http://idemo.cns.iu.edu/macroscopes/fleetmon.webm

**Comment by gurjaspalbedi** [comment]
@bherr2 ideamo.cns.iu.edu refused to connect for following URLs

http://idemo.cns.iu.edu/macroscopes/hathi/
![image.png](https://images.zenhubusercontent.com/5b9290b9fb5dec0b0d9cb85b/17f1650e-496d-4a9c-a58d-b85ed83e3817)

**Comment by bherr2** [comment]
I'm working on getting those opened up for iframe usage, but in the meantime (and perhaps is a better solution), you can use proxying via angular cil to load those: See [this](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md) and [this](https://itnext.io/angular-cli-proxy-configuration-4311acec9d6f). When deployed the proxying would be used since it'll be on the same origin and load just fine.

The urls would need to change to be `/macroscopes/xxx` instead of with a http in front.

**Comment by bherr2** [comment]
.webm files should load correctly now. Please use angular's proxying support for the macroscope urls loaded from the idemo server.
