### ISSUE TITLE
Use video tag for video macroscopes

### ISSUE THREAD

**Issue by bherr2** [cns-iu/macroscope-kiosk#64]
* [x] Use video tag
* [x] Use all available space
* [x] Disable download button
* [x] Disable option to go full-screen
* [x] Enable option to mute/unmute. Default is unmuted
* [x] Enable progress bar
* [x] Enable Play/Pause

**Comment by GagsdName** [comment]
Suggested - use https://github.com/videogular/videogular2

Videogular was also being used by the old version of macroscope-kiosk and supports Angular 6.
