### ISSUE TITLE
Some macroscopes cause the kiosk to freeze up after interacting with it for a time

### ISSUE THREAD

**Issue by bherr2** [cns-iu/macroscope-kiosk#75]
Not fully understood yet, but some macroscopes are causing the kiosk to freeze up. Need to investigate to determine the culprit.

**Comment by axdanbol** [comment]
As mentioned in pull, this was caused by idle timer emitting to many events.

**Comment by bherr2** [comment]
This did not fix it. I'm introducing a couple more issues to try and address the problem. 1) Gather logs and submit a formal bug to chromium and 2) use a kiosk OS (porteus-kiosk) that has the option of using chrome or firefox (and is better locked down).

**Comment by bherr2** [comment]
We've tracked this down to buggy Windows drivers for the touch screen. We're currently exploring other ways to address this (porteus-kiosk, fresh install of windows w/ no drivers, etc.)

**Comment by bherr2** [comment]
To address this, we moved from Windows to Ubuntu Linux. If freezes recur, create a new issue.
