### ISSUE TITLE
feedback from Leonard

### ISSUE THREAD

**Issue by GagsdName** [cns-iu/macroscope-kiosk#79]
From @lecross  - 
" I’ve reviewed the site with Lisel. This is what we came up with:
 
Logo crossbars in globe should be white not black, the logo on the attractor is correct (Waz up?)

Italics in modals (also need to do bold and international characters) - solution is to include these in the CSV file, both tags and entities (requires reactivating HTML feature)

Body text font size and line-height in modals (font-size: 1.125rem; line-height: 1.5em)

Modal width needs to be increased from 65rem to 75rem to accommodate the increase in font size

The top left link, Places & Spaces should be in italics (it was approved as is, this is a change)

When the modal is active it doesn't show (filter: blur(8px); blur wrapper

All headers, H1, H2, H3 will use font-family: "Montserrat"; all body text should be Lato
The H1 on the attractor, and the H2 headers on the modals should have a font-weight of 700; the h2 on the attractor should remain 400.

Modal text should change from More info to Less info
 
If there are questions, let me know."

**Comment by bherr2** [comment]
This is already done (by me)
