### ISSUE TITLE
File bug report on bugs.chromium.org

### ISSUE THREAD

**Issue by bherr2** [cns-iu/macroscope-kiosk#82]
Gather logs and other backing information and submit a bug report on <https://bugs.chromium.org>. 

* <https://bugs.chromium.org/p/chromium/issues/list>
* Info on debugging chromium on windows: https://www.chromium.org/developers/how-tos/debugging-on-windows

After filing bug, please follow the issue and see if we can get some information on how to fix it.

**Comment by GagsdName** [comment]
How about doing it this way - 
https://support.google.com/chrome/answer/95315?co=GENIE.Platform%3DDesktop&hl=en

**Comment by bherr2** [comment]
We've decided to use Ubuntu Linux as the host OS where this is not an issue.
