### ISSUE TITLE
Deploy compodoc documentation site to github pages

### ISSUE THREAD

**Issue by bherr2** [cns-iu/macroscope-kiosk#84]
* [ ] On commit to `master`, build the compodoc documentation and publish to gh-pages using Travis CI.
* [x] Update the README.md to point to the documentation site as a pill like the other links.

**Comment by bherr2** [comment]
Start off with building and merging documentation into a separate branch (`PBI-84-documentation`) so we can perfect the documentation before pushing to master. Travis can be pointed to use that branch to build the doc site until its merged into master.

**Comment by KalaRaja** [comment]
made a 'document' branch for documentation changes. We will open a pull request to 'master'  when we have atleast 60% doc coverage on 'develop'.
this is to prevent travis from continually rebuild the kiosk upon adding documentation.

**Comment by bherr2** [comment]
Looks good, but please:
* Update the README.md to point to the documentation site as a pill like the other links.

**Comment by bherr2** [comment]
This is done. Once we get the documentation level to 60% we'll change the branch on travis to `master`.
